version: '2.3'
services:
  nginx:
    image: 'nginx:stable-alpine'
    ports:
    - '3000:80'
    volumes:
    - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  moonshot-ha:
    scale: 3
    command: yarn watch
    volumes:
    - .:/app
    working_dir: /app
    restart: always
    image: 'node:10-alpine'
    # build: ./
    volumes:
      - .:/app
    links:
      - mongo
      - redis
    environment:
      - LISTEN_ADDRESS=${LISTEN_ADDRESS}
      - LISTEN_PORT=${LISTEN_PORT}
      - DEBUG=${DEBUG}
      - MONGODB_HOSTNAME=${MONGODB_HOSTNAME}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_NAME=${MONGODB_NAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - ALLOWED_DOMAINS=${ALLOWED_DOMAINS}
  redis:
    image: 'redis:alpine'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
